# Generated by Django 6.0.3 on 2026-03-12 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Upload your MP3 file here.",
                        upload_to="album_tracks/",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="blog.albumofthemonth",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
