# Generated by Django 6.0.3 on 2026-03-12 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_albumtrack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumtrack",
            name="audio_file",
            field=models.FileField(
                help_text="Upload your audio file here.",
                upload_to="album_tracks/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "mp4",
                            "wav",
                            "ogg",
                            "m4a",
                            "aac",
                            "flac",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="albumtrack",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Will auto-increment if left at 0."
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="audio_file",
            field=models.FileField(
                upload_to="tracks/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "mp4",
                            "wav",
                            "ogg",
                            "m4a",
                            "aac",
                            "flac",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Will auto-increment if left at 0."
            ),
        ),
    ]
