# Generated by Django 6.0.4 on 2026-04-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_albumtrack_audio_file_alter_albumtrack_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="playlist_type",
            field=models.CharField(
                choices=[
                    ("playlist", "Playlist"),
                    ("bande_originale", "Bande Originale"),
                    ("mixtape", "Mixtape"),
                ],
                default="playlist",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_image",
            field=models.ImageField(
                blank=True,
                help_text="Image to display while playing this track (playlist/mixtape mode).",
                null=True,
                upload_to="track_images/",
            ),
        ),
    ]
