# Generated by Django 6.0.3 on 2026-04-03 09:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_albumtrack_audio_file_alter_albumtrack_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumofthemonth",
            name="month",
            field=models.DateField(
                help_text="Le mois que cet album représente (utilisez le 1er du mois)."
            ),
        ),
        migrations.AlterField(
            model_name="albumtrack",
            name="audio_file",
            field=models.FileField(
                help_text="Uploadez votre fichier audio ici.",
                upload_to="album_tracks/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "mp4",
                            "wav",
                            "ogg",
                            "m4a",
                            "aac",
                            "flac",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="albumtrack",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="S'auto-incrémentera si laissé à 0."
            ),
        ),
        migrations.AlterField(
            model_name="movieimage",
            name="playlist",
            field=models.ForeignKey(
                help_text="Uniquement pour les Bandes Originales.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_images",
                to="blog.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="playlist_type",
            field=models.CharField(
                choices=[
                    ("playlist", "Playlist"),
                    ("bande_originale", "Bande Originale (Diaporama)"),
                    ("mixtape", "Mixtape"),
                ],
                default="playlist",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="S'auto-incrémentera si laissé à 0."
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_image",
            field=models.ImageField(
                blank=True,
                help_text="Image à afficher pendant la lecture de cette piste (mode classique).",
                null=True,
                upload_to="track_images/",
            ),
        ),
        migrations.CreateModel(
            name="AlbumPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="album_photos/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="blog.albumofthemonth",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
