# Generated by Django 6.0.3 on 2026-03-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_albumtrack_audio_file_alter_albumtrack_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="playlists/",
                verbose_name="Image de Couverture",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="playlist_type",
            field=models.CharField(
                choices=[
                    ("playlist", "Playlist"),
                    ("bande_originale", "Bande Originale"),
                    ("mixtapes", "Mixtapes"),
                ],
                default="playlist",
                max_length=20,
                verbose_name="Type de Playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.CreateModel(
            name="AtHomeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="albums_athome/", verbose_name="Image At Home"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athome_images",
                        to="blog.albumofthemonth",
                        verbose_name="Album",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
