# Generated by Django 6.0.4 on 2026-04-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_albumtrack_audio_file_alter_albumtrack_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="playlist_type",
            field=models.CharField(
                choices=[
                    ("playlist", "Playlist"),
                    ("bande_originale", "Bande Originale"),
                    ("mixtape", "Mixtape"),
                ],
                default="playlist",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AtHomeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="at_home_images/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "album",
                    models.ForeignKey(
                        help_text="At home multiple photos.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="at_home_images",
                        to="blog.albumofthemonth",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
