# Generated by Django 6.0.5 on 2026-05-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_playlist_playlist_type_albumimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="albumofthemonth",
            name="at_home_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo to display in the 'At home' section.",
                null=True,
                upload_to="albums/",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="track",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
