# Generated by Django 6.0.3 on 2026-05-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_movieimage_playlist_and_more'),
        ('blog', '0005_albumofthemonth_at_home_image_track_artist_and_more'),
    ]

    operations = [
    ]
