# Generated by Django 6.0.5 on 2026-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_merge_20260507_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="playlist_type",
            field=models.CharField(
                choices=[
                    ("playlist", "Playlist"),
                    ("bande_originale", "Bande Originale"),
                    ("mixtape", "Mixtape"),
                ],
                default="playlist",
                max_length=15,
            ),
        ),
    ]
