# Generated by Django 6.0.6 on 2026-06-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_playlist_playlist_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="albumofthemonth",
            options={"ordering": ["-month", "title"]},
        ),
    ]
